---
- name: Install nodesource rpm
  yum:
    name: "http://rpm.nodesource.com/pub_{{ nodejs_major_version }}.x/el/{{ ansible_distribution_major_version }}/x86_64/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present

- name: Install nodejs
  yum: name=nodejs state=present
