# local_action では Erlang は RHEL7 を取得する
- block:
    # Download erlang rpm of RHEL7
    - local_action: get_url url={{ rabbitmq_erlang_rpm_url }} dest={{ role_path }}/files/{{ rabbitmq_erlang_rpm }}

    # Download rabbitmq rpm
    - local_action: get_url url={{ rabbitmq_rpm_url }} dest={{ role_path }}/files/{{ rabbitmq_rpm }}

  become: false
  environment: "{{ proxy_env }}"
  tags:
    - local_download
