---
- include_vars: "../vars/rhel{{ ansible_distribution_major_version }}.yml"

- name: Ensure download dir
  file: name=/opt/download state=directory

# Local ダウンロード
- include: local_download.yml
  when: local_download

# Local RPM が存在するか確認する
- name: Check if local RPM exists
  local_action: stat path={{ role_path }}/files/{{ rabbitmq_rpm }}
  register: local_rpm
  become: false

# インストール
- include: local_install.yml
  when: local_rpm.stat.exists

- include: download_install.yml
  when: not local_rpm.stat.exists

# 設定を投入する
- name: Install RabbitMQ config
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: restart_rabbitmq_server

- name: Install Erlang Cookie for cluster
  template: src=erlang.cookie.j2 dest=/var/lib/rabbitmq/.erlang.cookie owner=rabbitmq group=rabbitmq mode=0600
  notify: restart_rabbitmq_server

- name: Enable RabbitMQ Server
  service: name=rabbitmq-server enabled=yes state=started
