---
# Tomcat: バージョン
tomcat_major_version: 9
tomcat_version: 9.0.80

# Tomcat: 待ち受けポート
tomcat_port: 8080

# Tomcat: 最大スレッド数
tomcat_max_threads: 2000
# Tomcat: 最大コネクション数
tomcat_max_connections: 2000

# Tomcat: 最大メモリ量(-Xmx)
tomcat_max_memory: '2048m'
# Tomcat: 最小メモリ量(-Xms)
tomcat_min_memory: '1024m'
# Tomcat: 追加JVMオプション
tomcat_jvm_options: ''

# Tomcat: HTTPSリバースプロキシ使用設定(ELBなど)
tomcat_https_revproxy: False

# Tomcat JAVA_OPTS
tomcat_memory: "-Xmx{{ tomcat_max_memory }} -Xms{{ tomcat_min_memory }}"
tomcat_gc: "-XX:+UseConcMarkSweepGC"
tomcat_gclog: "-Xloggc:/var/log/tomcat/gc.log.%t -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=10M"
tomcat_heapdump: "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/log/tomcat"

tomcat_java_opts: "-Djava.awt.headless=true {{ tomcat_memory }} {{ tomcat_gc }} {{ tomcat_gclog }} {{ tomcat_heapdump }} {{ tomcat_jvm_options }}"

#  -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9012 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
