---
tomcat9_basename: "apache-tomcat-{{ tomcat9_version }}"
tomcat9_tarball: "{{ tomcat9_basename }}.tar.gz"
tomcat9_url: "http://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat9_version }}/bin/{{ tomcat9_tarball }}"
