---
# centosの構築手順（ https://docs.docker.com/engine/installation/linux/centos/ )を参照

# device-mapperのインストール(古いバージョンの場合は、dockerが起動できない場合がある)
#- name: Install device-mapper
#  yum:
#    name: device-mapper
#    enablerepo: epel
#    state: latest
#  tags:
#    - docker

# Install yum-utils
- name: Install yum-utils
  yum:
    name: yum-utils
    state: present
  tags:
    - docker

# Install docker ce repo
- name: Add docker yum repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
  tags:
    - docker

# Docker CE インストールとサービス設定
- block:
  # Install docker ce
  - name: Install latest docker-ce
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        #- docker-compose-plugin
      state: present

  # Dockerサービスの設定ファイルのディレクトリの作成
  - name: Create directory for docker service supplementary config
    file:
      path:  /etc/systemd/system/docker.service.d
      owner: root
      group: root
      mode:  0755
      state: directory

  # Dockerサービスの設定ファイルの適用
  #- name: Create docker service supplementary config file
  #  template:
  #    src:   docker.service.conf.j2
  #    dest:  /etc/systemd/system/docker.service.d/docker.service.conf
  #    owner: root
  #    group: root
  #   mode:  0644
  #  register: docker_conf

  # Dockerのプロキシの適用
  - name: Create docker http proxy supplementary config file
    template:
      src:   docker.http-proxy.conf.j2
      dest:  /etc/systemd/system/docker.service.d/docker.http-proxy.conf
      owner: root
      group: root
      mode:  0644
    register: docker_proxy_conf
    when: proxy_env is defined

  tags:
    - docker
