# epel-releaseの更新(CentOS)
- name: Install epel-release repository configuration (CentOS)
  yum:
    name: "https://ftp.yz.yamagata-u.ac.jp/pub/linux/fedora-projects/epel/epel-release-latest-7.noarch.rpm"
    state: present

