# epel-releaseの更新
- name: Install epel-release repository configuration
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: true
    state: present
